spring.profiles.active: dev

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ebook_chat
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  session:
    store-type: redis

  thymeleaf:
    cache: false

  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: true

ebook:
  chat:
    relay:
      host: localhost
      port: 61613

spring.flyway.enabled: true